apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: bert-demo
spec:
  rules:
    - host: bert-demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: bert-demo
                port:
                  number: 80
